import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home, Bath, FileText, Users, Settings, Plus, Search, Trash2, Printer, Save, ChevronRight, Calculator, Building2, Truck, Hammer, Database, Sparkles} from 'lucide-react';
import './styles.css';
import catalogData from './catalog.json';
import type {Catalog,Project,Option,Quote} from './types';

const money=(n:number)=>new Intl.NumberFormat('ru-RU').format(Math.round(n))+' ₽';
const uid=()=>`DP-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;

function App(){
 const [catalog,setCatalog]=useState<Catalog|null>(null); const [view,setView]=useState('catalog');
 const [kind,setKind]=useState<'ready'|'custom'>('ready'); const [project,setProject]=useState<Project|null>(null);
 const [selected,setSelected]=useState<string[]>([]); const [search,setSearch]=useState('');
 const [client,setClient]=useState({name:'',phone:'',email:''}); const [external,setExternal]=useState({delivery:0,foundation:0,montage:0});
 const [custom,setCustom]=useState({name:'Индивидуальный проект',base:0,area:0,modules:1,length:'',width:'',height:'2700',rooms:'',foundation:'',color:'',notes:''});
 const [quotes,setQuotes]=useState<any[]>([]); const [toast,setToast]=useState('');
 useEffect(()=>{setCatalog(catalogData as Catalog); try{setQuotes(JSON.parse(localStorage.getItem('dp_quotes')||'[]'));}catch{}},[]);
 const activeProject=project;
 const options=useMemo(()=>catalog?.options||[],[catalog]);
 const optionTotal=selected.reduce((s,id)=>s+(options.find(o=>o.id===id)?.price||0),0);
 const base=kind==='ready'?(activeProject?.price||0):custom.base;
 const total=base+optionTotal+external.delivery+external.foundation+external.montage;
 const filteredProjects=useMemo(()=>{
   if(!catalog)return[]; const q=search.toLowerCase(); return catalog.projects.filter(p=>!q||p.name.toLowerCase().includes(q)||p.family.toLowerCase().includes(q));
 },[catalog,search]);
 const chooseProject=(p:Project)=>{setProject(p);setKind('ready');setSelected([]);setView('config');};
 const reset=()=>{setProject(null);setSelected([]);setClient({name:'',phone:'',email:''});setExternal({delivery:0,foundation:0,montage:0});setCustom({name:'Индивидуальный проект',base:0,area:0,modules:1,length:'',width:'',height:'2700',rooms:'',foundation:'',color:'',notes:''});setView('catalog');};
 const saveQuote=async()=>{const q:Quote={number:uid(),kind,client:client.name,phone:client.phone,email:client.email,project:kind==='ready'?(project?.name||''):custom.name,base,items:selected.map(id=>{const o=options.find(x=>x.id===id)!;return{name:o.name,price:o.price,calc:o.calc}}),external:[\n     external.delivery ? {name:'Доставка',price:external.delivery} : null,\n     external.foundation ? {name:'Фундамент',price:external.foundation} : null,\n     external.montage ? {name:'Монтаж',price:external.montage} : null\n   ].filter(Boolean) as {name:string;price:number}[],notes:kind==='custom'?custom.notes:'',manager:'Менеджер DP MODULE',createdAt:new Date().toISOString()};
   const saved={...q,total,id:Date.now(),created_at:new Date().toISOString()}; const next=[saved,...quotes]; setQuotes(next); localStorage.setItem('dp_quotes',JSON.stringify(next)); localStorage.setItem('dp_last_quote',JSON.stringify(saved)); setToast('КП сохранено в браузере'); setTimeout(()=>setToast(''),1800);
 };
 if(!catalog)return <div className="loading"><div className="logo">DP <b>MODULE</b></div><p>Загружаем каталог…</p></div>;
 return <div className="shell">
   <header><div className="brand">DP <span>MODULE</span><small> SALES</small></div><div className="header-actions"><span className="status"><i/> база подключена</span><button className="ghost" onClick={reset}>Новый расчёт</button></div></header>
   <aside>
    <Nav active={view==='catalog'||view==='config'} icon={<Home/>} text="Каталог" onClick={()=>setView('catalog')}/>
    <Nav active={view==='custom'} icon={<Sparkles/>} text="Свой проект" onClick={()=>{setKind('custom');setProject(null);setView('custom')}}/>
    <Nav active={view==='quotes'} icon={<FileText/>} text="КП" onClick={()=>setView('quotes')}/>
    <Nav active={view==='clients'} icon={<Users/>} text="Клиенты" onClick={()=>setView('clients')}/>
    <div className="nav-section">Система</div><Nav active={view==='settings'} icon={<Settings/>} text="Настройки" onClick={()=>setView('settings')}/>
    <div className="side-note"><Database size={16}/><span>React + Vite + LocalStorage<br/><b>не статичная HTML-страница</b></span></div>
   </aside>
   <main>
    {view==='catalog'&&<CatalogView catalog={catalog} search={search} setSearch={setSearch} onChoose={chooseProject}/>} 
    {view==='custom'&&<CustomView custom={custom} setCustom={setCustom} onContinue={()=>setView('config')}/>} 
    {view==='config'&&<ConfigView kind={kind} project={project} custom={custom} catalog={catalog} selected={selected} setSelected={setSelected} client={client} setClient={setClient} external={external} setExternal={setExternal} total={total} optionTotal={optionTotal} onSave={saveQuote} onPrint={()=>setView('quote')}/>} 
    {view==='quote'&&<QuoteView kind={kind} project={project} custom={custom} client={client} catalog={catalog} selected={selected} external={external} total={total} onBack={()=>setView('config')}/>} 
    {view==='quotes'&&<QuotesView quotes={quotes}/>} 
    {view==='clients'&&<ClientsView/>}
    {view==='settings'&&<SettingsView/>}
   </main>
   {view==='config'&&<aside className="right"><div className="eyebrow">ТЕКУЩИЙ РАСЧЁТ</div><div className="calc-title">{kind==='ready'?project?.name:'Индивидуальный проект'}</div><div className="total">{money(total)}</div><div className="muted">База + выбранные опции + внешние расходы</div><div className="sumline"><span>База</span><b>{money(base)}</b></div><div className="sumline"><span>Опции</span><b>{money(optionTotal)}</b></div><div className="sumline"><span>Доставка / фундамент / монтаж</span><b>{money(external.delivery+external.foundation+external.montage)}</b></div><button className="primary full" onClick={saveQuote}><Save size={17}/> Сохранить КП</button><button className="secondary full" onClick={()=>setView('quote')}><FileText size={17}/> Предпросмотр КП</button></aside>}
   {toast&&<div className="toast">✓ {toast}</div>}
 </div>
}
function Nav({active,icon,text,onClick}:{active:boolean;icon:any;text:string;onClick:()=>void}){return <button className={'nav '+(active?'active':'')} onClick={onClick}>{icon}<span>{text}</span></button>}
function CatalogView({catalog,search,setSearch,onChoose}:{catalog:Catalog;search:string;setSearch:(s:string)=>void;onChoose:(p:Project)=>void}){const [tab,setTab]=useState('house');const fams=catalog.families.filter(f=>f.type===tab);const ids=new Set(fams.map(f=>f.id));const ps=catalog.projects.filter(p=>ids.has(p.family));return <><div className="pagehead"><div><div className="eyebrow">ОТДЕЛ ПРОДАЖ</div><h1>Каталог DP MODULE</h1><p>Выберите готовую модель — затем соберите комплектацию и КП.</p></div><div className="search"><Search size={18}/><input placeholder="Поиск проекта…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="tabs"><button className={tab==='house'?'on':''} onClick={()=>setTab('house')}><Home/> Дома</button><button className={tab==='bath'?'on':''} onClick={()=>setTab('bath')}><Bath/> Бани</button></div><div className="family-row">{fams.map(f=><button key={f.id} className="family" onClick={()=>setSearch(f.name)}><img src={f.cover}/><span>{f.name}</span><small>от {money(f.from)}</small></button>)}</div><div className="grid">{ps.filter(p=>!search||p.name.toLowerCase().includes(search.toLowerCase())||fams.some(f=>f.id===p.family&&f.name.toLowerCase().includes(search.toLowerCase()))).map(p=><ProjectCard key={p.id} p={p} onChoose={onChoose}/>)}</div></>}
function ProjectCard({p,onChoose}:{p:Project;onChoose:(p:Project)=>void}){return <article className="project"><img src={`assets/p-${p.page}.jpg`}/><div className="project-body"><div className="eyebrow">ГОТОВЫЙ ПРОЕКТ</div><h3>{p.name}</h3><div className="meta"><span>{p.area} м²</span><span>{p.dimensions}</span></div><strong>{money(p.price)}</strong><button className="primary" onClick={()=>onChoose(p)}>Собрать КП <ChevronRight size={17}/></button></div></article>}
function CustomView({custom,setCustom,onContinue}:{custom:any;setCustom:any;onContinue:()=>void}){return <><div className="pagehead"><div><div className="eyebrow">КОНСТРУКТОР</div><h1>Свой проект</h1><p>Здесь менеджер задаёт переменные. Если цены нет в каталоге, она вводится как согласованная вручную позиция.</p></div></div><div className="form-card"><div className="section-title">Основные параметры</div><div className="fields"><Field label="Название проекта"><input value={custom.name} onChange={e=>setCustom({...custom,name:e.target.value})}/></Field><Field label="База проекта, ₽"><input type="number" value={custom.base} onChange={e=>setCustom({...custom,base:+e.target.value})}/></Field><Field label="Площадь, м²"><input type="number" value={custom.area} onChange={e=>setCustom({...custom,area:+e.target.value})}/></Field><Field label="Количество модулей"><input type="number" min="1" value={custom.modules} onChange={e=>setCustom({...custom,modules:+e.target.value})}/></Field><Field label="Длина"><input value={custom.length} onChange={e=>setCustom({...custom,length:e.target.value})}/></Field><Field label="Ширина"><input value={custom.width} onChange={e=>setCustom({...custom,width:e.target.value})}/></Field><Field label="Высота, мм"><input value={custom.height} onChange={e=>setCustom({...custom,height:e.target.value})}/></Field><Field label="Фундамент"><select value={custom.foundation} onChange={e=>setCustom({...custom,foundation:e.target.value})}><option value="">Не выбран</option><option>Свайно-винтовой</option><option>Существующий</option><option>Другое</option></select></Field><Field label="Комнаты / назначение"><input value={custom.rooms} onChange={e=>setCustom({...custom,rooms:e.target.value})}/></Field><Field label="Цвет фасада"><input value={custom.color} onChange={e=>setCustom({...custom,color:e.target.value})}/></Field></div><Field label="Пожелания клиента"><textarea value={custom.notes} onChange={e=>setCustom({...custom,notes:e.target.value})}/></Field><div className="notice">Индивидуальная цена не рассчитывается автоматически по общему тарифу: источник должен быть согласован менеджером/конструктором. Это защищает КП от выдуманных цен.</div><button className="primary" onClick={onContinue}>Перейти к комплектации <ChevronRight size={17}/></button></div></>}
function ConfigView({kind,project,custom,catalog,selected,setSelected,client,setClient,external,setExternal,total,optionTotal,onSave,onPrint}:{kind:any;project:any;custom:any;catalog:Catalog;selected:string[];setSelected:any;client:any;setClient:any;external:any;setExternal:any;total:number;optionTotal:number;onSave:()=>void;onPrint:()=>void}){const toggle=(id:string)=>setSelected((s:string[])=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);return <><div className="pagehead"><div><div className="eyebrow">КОМПЛЕКТАЦИЯ</div><h1>{kind==='ready'?project?.name:'Индивидуальный проект'}</h1><p>{kind==='ready'?`${project.area} м² · ${project.dimensions} · ${money(project.price)} базовая стоимость`:`${custom.modules} мод. · ${custom.area} м² · ${custom.length||'—'} × ${custom.width||'—'} × ${custom.height} мм`}</p></div></div><div className="config-grid"><div><section className="form-card"><div className="section-title">Клиент</div><div className="fields"><Field label="Имя"><input value={client.name} onChange={e=>setClient({...client,name:e.target.value})}/></Field><Field label="Телефон"><input value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})}/></Field><Field label="Email"><input value={client.email} onChange={e=>setClient({...client,email:e.target.value})}/></Field></div></section><section className="form-card"><div className="section-title">Дополнительные опции</div>{catalog.options.map(o=><label className="option" key={o.id}><span><input type="checkbox" checked={selected.includes(o.id)} onChange={()=>toggle(o.id)}/><b>{o.name}</b><small>{o.group} · {o.calc}</small></span><strong>{money(o.price)}</strong></label>)}</section></div><div><section className="form-card"><div className="section-title">Отдельные расходы</div><Expense icon={<Truck/>} label="Доставка" value={external.delivery} setValue={(v:number)=>setExternal({...external,delivery:v})}/><Expense icon={<Building2/>} label="Фундамент" value={external.foundation} setValue={(v:number)=>setExternal({...external,foundation:v})}/><Expense icon={<Hammer/>} label="Монтаж" value={external.montage} setValue={(v:number)=>setExternal({...external,montage:v})}/><div className="notice">Суммы доставки, фундамента и монтажа не являются универсальным тарифом. Вводите согласованную сумму по конкретному объекту.</div></section><section className="form-card"><div className="section-title">Действия</div><button className="primary full" onClick={onSave}><Save size={17}/> Сохранить</button><button className="secondary full" onClick={onPrint}><Printer size={17}/> Сформировать КП</button></section></div></div></>}
function Expense({icon,label,value,setValue}:{icon:any;label:string;value:number;setValue:(v:number)=>void}){return <div className="expense"><span>{icon}<b>{label}</b></span><input type="number" value={value||''} placeholder="0" onChange={e=>setValue(+e.target.value)}/></div>}
function Field({label,children}:{label:string;children:any}){return <label className="field"><span>{label}</span>{children}</label>}
function QuoteView({kind,project,custom,client,catalog,selected,external,total,onBack}:{kind:any;project:any;custom:any;client:any;catalog:Catalog;selected:string[];external:any;total:number;onBack:()=>void}){const opts=catalog.options.filter(o=>selected.includes(o.id));return <div className="quote-wrap"><div className="quote-toolbar"><button className="secondary" onClick={onBack}>← Назад</button><button className="primary" onClick={()=>window.print()}><Printer size={17}/> Печать / PDF</button></div><article className="quote"><div className="quote-cover"><div className="logo">DP <b>MODULE</b></div><div><div className="eyebrow">КОММЕРЧЕСКОЕ ПРЕДЛОЖЕНИЕ</div><h1>{kind==='ready'?project?.name:'Индивидуальный проект'}</h1><p>Персональная комплектация для {client.name||'клиента'}.</p></div><div className="cover-total"><span>Стоимость по текущему расчёту</span><b>{money(total)}</b></div></div><section><div className="quote-title">01 / КОНФИГУРАЦИЯ</div><h2>{kind==='ready'?project?.name:custom.name}</h2><div className="quote-grid"><div><b>Клиент</b><span>{client.name||'—'}</span></div><div><b>Телефон</b><span>{client.phone||'—'}</span></div><div><b>Площадь</b><span>{kind==='ready'?`${project?.area} м²`:custom.area?`${custom.area} м²`:'—'}</span></div><div><b>Модули</b><span>{kind==='ready'?'по проекту':custom.modules}</span></div></div></section><section><div className="quote-title">02 / СТОИМОСТЬ</div><table><tbody><tr><td>Базовая комплектация</td><td>{money(kind==='ready'?project.price:custom.base)}</td></tr>{opts.map(o=><tr key={o.id}><td>{o.name}<small>{o.calc}</small></td><td>{money(o.price)}</td></tr>)}{external.delivery>0&&<tr><td>Доставка</td><td>{money(external.delivery)}</td></tr>}{external.foundation>0&&<tr><td>Фундамент</td><td>{money(external.foundation)}</td></tr>}{external.montage>0&&<tr><td>Монтаж</td><td>{money(external.montage)}</td></tr>}<tr className="grand"><td>ИТОГО</td><td>{money(total)}</td></tr></tbody></table></section><section><div className="quote-title">03 / ВАЖНО</div><p>Финальная стоимость и состав работ фиксируются после согласования проекта, комплектации и технических условий. Для индивидуальных решений требуется подтверждение конструктора.</p>{kind==='custom'&&custom.notes&&<div className="client-note"><b>Пожелания клиента</b><p>{custom.notes}</p></div>}</section><footer>DP MODULE · Коммерческое предложение · {new Date().toLocaleDateString('ru-RU')}</footer></article></div>}
function QuotesView({quotes}:{quotes:any[]}){return <><div className="pagehead"><div><div className="eyebrow">ИСТОРИЯ</div><h1>Коммерческие предложения</h1><p>КП сохраняются в браузере этого устройства.</p></div></div><div className="table-card"><table><thead><tr><th>Номер</th><th>Клиент</th><th>Проект</th><th>Сумма</th><th>Создано</th></tr></thead><tbody>{quotes.map(q=><tr key={q.id}><td><b>{q.number}</b></td><td>{q.client||'—'}<small>{q.phone}</small></td><td>{q.project}</td><td>{money(q.total)}</td><td>{q.created_at?new Date(q.created_at).toLocaleDateString('ru-RU'):'—'}</td></tr>)}</tbody></table>{!quotes.length&&<div className="empty">Пока нет сохранённых КП.</div>}</div></>}
function ClientsView(){const [clients,setClients]=useState<any[]>(()=>{try{return JSON.parse(localStorage.getItem('dp_clients')||'[]')}catch{return []}}); const [form,setForm]=useState({name:'',phone:'',email:'',note:''}); const [saved,setSaved]=useState(false); const add=()=>{const c={...form,id:Date.now(),created_at:new Date().toISOString()}; const next=[c,...clients];setClients(next);localStorage.setItem('dp_clients',JSON.stringify(next));setForm({name:'',phone:'',email:'',note:''});setSaved(true);setTimeout(()=>setSaved(false),1500)}; return <><div className="pagehead"><div><div className="eyebrow">CRM</div><h1>Клиенты</h1><p>В GitHub Pages данные сохраняются локально в браузере этого устройства.</p></div></div><div className="form-card"><div className="fields"><Field label="Имя"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Телефон"><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Email"><input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field></div><Field label="Комментарий"><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></Field><button className="primary" onClick={add}><Plus size={17}/> Сохранить клиента</button>{saved&&<span className="saved">Сохранено</span>}</div><div className="table-card"><table><thead><tr><th>Имя</th><th>Телефон</th><th>Email</th><th>Комментарий</th></tr></thead><tbody>{clients.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.phone}</td><td>{c.email}</td><td>{c.note}</td></tr>)}</tbody></table></div></>}
function SettingsView(){return <><div className="pagehead"><div><div className="eyebrow">СИСТЕМА</div><h1>Настройки</h1><p>Архитектура подготовлена под дальнейшее подключение полноценной админки прайсов.</p></div></div><div className="settings-grid"><div className="form-card"><div className="section-title">Что уже подключено</div><ul><li>React + TypeScript</li><li>GitHub Pages / Vite</li><li>LocalStorage для КП и клиентов</li><li>Каталог вынесен в JSON</li><li>Печать КП через отдельный документ</li><li>Готовые проекты и индивидуальный режим</li></ul></div><div className="form-card"><div className="section-title">Следующий уровень</div><ul><li>Авторизация менеджеров</li><li>Роли менеджер / руководитель / администратор</li><li>Редактор цен и правил</li><li>Версионирование прайса</li><li>Полноценный PDF renderer</li><li>Экспорт в CRM</li></ul></div></div></>}
class ErrorBoundary extends React.Component<React.PropsWithChildren, {error:string|null}>{
 static getDerivedStateFromError(error:unknown){ return {error:error instanceof Error ? `${error.name}: ${error.message}` : String(error)}; }
 state={error:null};
 render(){ if(this.state.error) return <div style={{fontFamily:'system-ui',padding:40,maxWidth:900,margin:'auto'}}><h1>DP MODULE — ошибка запуска</h1><p>Приложение не смогло загрузиться.</p><pre style={{whiteSpace:'pre-wrap',background:'#f4f4f4',padding:16,borderRadius:8}}>{this.state.error}</pre><p>Откройте консоль браузера (F12 → Console) и пришлите скриншот, если ошибка повторится.</p></div>; return this.props.children; }
}
createRoot(document.getElementById('root')!).render(<ErrorBoundary><App/></ErrorBoundary>);
